name: build-actions
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Install dependencies
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Update npm
        run: npm install --global npm@latest
      - name: patch node gyp on windows to support Visual Studio 2019
        shell: powershell
        run: |
          npm install --global node-gyp@latest
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run make --platform win32
      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          files: |
            out/make/squirrel.windows/x64/anime-app.exe
